/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SpaceUtil type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpaceUtil{}

// SpaceUtil DOCSTRING
type SpaceUtil struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
	Blocks []BlockUtil `json:"blocks"`
	Size int32 `json:"size"`
	Used int32 `json:"used"`
}

type _SpaceUtil SpaceUtil

// NewSpaceUtil instantiates a new SpaceUtil object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpaceUtil(name string, desc string, blocks []BlockUtil, size int32, used int32) *SpaceUtil {
	this := SpaceUtil{}
	this.Name = name
	this.Desc = desc
	this.Blocks = blocks
	this.Size = size
	this.Used = used
	return &this
}

// NewSpaceUtilWithDefaults instantiates a new SpaceUtil object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpaceUtilWithDefaults() *SpaceUtil {
	this := SpaceUtil{}
	return &this
}

// GetName returns the Name field value
func (o *SpaceUtil) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SpaceUtil) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SpaceUtil) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *SpaceUtil) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *SpaceUtil) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *SpaceUtil) SetDesc(v string) {
	o.Desc = v
}

// GetBlocks returns the Blocks field value
func (o *SpaceUtil) GetBlocks() []BlockUtil {
	if o == nil {
		var ret []BlockUtil
		return ret
	}

	return o.Blocks
}

// GetBlocksOk returns a tuple with the Blocks field value
// and a boolean to check if the value has been set.
func (o *SpaceUtil) GetBlocksOk() ([]BlockUtil, bool) {
	if o == nil {
		return nil, false
	}
	return o.Blocks, true
}

// SetBlocks sets field value
func (o *SpaceUtil) SetBlocks(v []BlockUtil) {
	o.Blocks = v
}

// GetSize returns the Size field value
func (o *SpaceUtil) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *SpaceUtil) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *SpaceUtil) SetSize(v int32) {
	o.Size = v
}

// GetUsed returns the Used field value
func (o *SpaceUtil) GetUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *SpaceUtil) GetUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *SpaceUtil) SetUsed(v int32) {
	o.Used = v
}

func (o SpaceUtil) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpaceUtil) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["blocks"] = o.Blocks
	toSerialize["size"] = o.Size
	toSerialize["used"] = o.Used
	return toSerialize, nil
}

func (o *SpaceUtil) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"blocks",
		"size",
		"used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpaceUtil := _SpaceUtil{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpaceUtil)

	if err != nil {
		return err
	}

	*o = SpaceUtil(varSpaceUtil)

	return err
}

type NullableSpaceUtil struct {
	value *SpaceUtil
	isSet bool
}

func (v NullableSpaceUtil) Get() *SpaceUtil {
	return v.value
}

func (v *NullableSpaceUtil) Set(val *SpaceUtil) {
	v.value = val
	v.isSet = true
}

func (v NullableSpaceUtil) IsSet() bool {
	return v.isSet
}

func (v *NullableSpaceUtil) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpaceUtil(val *SpaceUtil) *NullableSpaceUtil {
	return &NullableSpaceUtil{value: val, isSet: true}
}

func (v NullableSpaceUtil) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpaceUtil) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


