/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SpaceExpand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpaceExpand{}

// SpaceExpand DOCSTRING
type SpaceExpand struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
	Blocks []BlockExpand `json:"blocks"`
}

type _SpaceExpand SpaceExpand

// NewSpaceExpand instantiates a new SpaceExpand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpaceExpand(name string, desc string, blocks []BlockExpand) *SpaceExpand {
	this := SpaceExpand{}
	this.Name = name
	this.Desc = desc
	this.Blocks = blocks
	return &this
}

// NewSpaceExpandWithDefaults instantiates a new SpaceExpand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpaceExpandWithDefaults() *SpaceExpand {
	this := SpaceExpand{}
	return &this
}

// GetName returns the Name field value
func (o *SpaceExpand) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SpaceExpand) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SpaceExpand) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *SpaceExpand) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *SpaceExpand) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *SpaceExpand) SetDesc(v string) {
	o.Desc = v
}

// GetBlocks returns the Blocks field value
func (o *SpaceExpand) GetBlocks() []BlockExpand {
	if o == nil {
		var ret []BlockExpand
		return ret
	}

	return o.Blocks
}

// GetBlocksOk returns a tuple with the Blocks field value
// and a boolean to check if the value has been set.
func (o *SpaceExpand) GetBlocksOk() ([]BlockExpand, bool) {
	if o == nil {
		return nil, false
	}
	return o.Blocks, true
}

// SetBlocks sets field value
func (o *SpaceExpand) SetBlocks(v []BlockExpand) {
	o.Blocks = v
}

func (o SpaceExpand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpaceExpand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["blocks"] = o.Blocks
	return toSerialize, nil
}

func (o *SpaceExpand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"blocks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpaceExpand := _SpaceExpand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpaceExpand)

	if err != nil {
		return err
	}

	*o = SpaceExpand(varSpaceExpand)

	return err
}

type NullableSpaceExpand struct {
	value *SpaceExpand
	isSet bool
}

func (v NullableSpaceExpand) Get() *SpaceExpand {
	return v.value
}

func (v *NullableSpaceExpand) Set(val *SpaceExpand) {
	v.value = val
	v.isSet = true
}

func (v NullableSpaceExpand) IsSet() bool {
	return v.isSet
}

func (v *NullableSpaceExpand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpaceExpand(val *SpaceExpand) *NullableSpaceExpand {
	return &NullableSpaceExpand{value: val, isSet: true}
}

func (v NullableSpaceExpand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpaceExpand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


