/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExtNetExpand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtNetExpand{}

// ExtNetExpand DOCSTRING
type ExtNetExpand struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
	Space string `json:"space"`
	Block string `json:"block"`
	Cidr string `json:"cidr" validate:"regexp=x.x.x.x\\/x"`
	Subnets []ExtSubnet `json:"subnets"`
}

type _ExtNetExpand ExtNetExpand

// NewExtNetExpand instantiates a new ExtNetExpand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtNetExpand(name string, desc string, space string, block string, cidr string, subnets []ExtSubnet) *ExtNetExpand {
	this := ExtNetExpand{}
	this.Name = name
	this.Desc = desc
	this.Space = space
	this.Block = block
	this.Cidr = cidr
	this.Subnets = subnets
	return &this
}

// NewExtNetExpandWithDefaults instantiates a new ExtNetExpand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtNetExpandWithDefaults() *ExtNetExpand {
	this := ExtNetExpand{}
	return &this
}

// GetName returns the Name field value
func (o *ExtNetExpand) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ExtNetExpand) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ExtNetExpand) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *ExtNetExpand) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *ExtNetExpand) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *ExtNetExpand) SetDesc(v string) {
	o.Desc = v
}

// GetSpace returns the Space field value
func (o *ExtNetExpand) GetSpace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Space
}

// GetSpaceOk returns a tuple with the Space field value
// and a boolean to check if the value has been set.
func (o *ExtNetExpand) GetSpaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Space, true
}

// SetSpace sets field value
func (o *ExtNetExpand) SetSpace(v string) {
	o.Space = v
}

// GetBlock returns the Block field value
func (o *ExtNetExpand) GetBlock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Block
}

// GetBlockOk returns a tuple with the Block field value
// and a boolean to check if the value has been set.
func (o *ExtNetExpand) GetBlockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Block, true
}

// SetBlock sets field value
func (o *ExtNetExpand) SetBlock(v string) {
	o.Block = v
}

// GetCidr returns the Cidr field value
func (o *ExtNetExpand) GetCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value
// and a boolean to check if the value has been set.
func (o *ExtNetExpand) GetCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cidr, true
}

// SetCidr sets field value
func (o *ExtNetExpand) SetCidr(v string) {
	o.Cidr = v
}

// GetSubnets returns the Subnets field value
func (o *ExtNetExpand) GetSubnets() []ExtSubnet {
	if o == nil {
		var ret []ExtSubnet
		return ret
	}

	return o.Subnets
}

// GetSubnetsOk returns a tuple with the Subnets field value
// and a boolean to check if the value has been set.
func (o *ExtNetExpand) GetSubnetsOk() ([]ExtSubnet, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subnets, true
}

// SetSubnets sets field value
func (o *ExtNetExpand) SetSubnets(v []ExtSubnet) {
	o.Subnets = v
}

func (o ExtNetExpand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtNetExpand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["space"] = o.Space
	toSerialize["block"] = o.Block
	toSerialize["cidr"] = o.Cidr
	toSerialize["subnets"] = o.Subnets
	return toSerialize, nil
}

func (o *ExtNetExpand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"space",
		"block",
		"cidr",
		"subnets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtNetExpand := _ExtNetExpand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtNetExpand)

	if err != nil {
		return err
	}

	*o = ExtNetExpand(varExtNetExpand)

	return err
}

type NullableExtNetExpand struct {
	value *ExtNetExpand
	isSet bool
}

func (v NullableExtNetExpand) Get() *ExtNetExpand {
	return v.value
}

func (v *NullableExtNetExpand) Set(val *ExtNetExpand) {
	v.value = val
	v.isSet = true
}

func (v NullableExtNetExpand) IsSet() bool {
	return v.isSet
}

func (v *NullableExtNetExpand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtNetExpand(val *ExtNetExpand) *NullableExtNetExpand {
	return &NullableExtNetExpand{value: val, isSet: true}
}

func (v NullableExtNetExpand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtNetExpand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


