/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the User type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &User{}

// User DOCSTRING
type User struct {
	Id string `json:"id"`
	DarkMode bool `json:"darkMode"`
	ApiRefresh int32 `json:"apiRefresh"`
	IsAdmin bool `json:"isAdmin"`
}

type _User User

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser(id string, darkMode bool, apiRefresh int32, isAdmin bool) *User {
	this := User{}
	this.Id = id
	this.DarkMode = darkMode
	this.ApiRefresh = apiRefresh
	this.IsAdmin = isAdmin
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetId returns the Id field value
func (o *User) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *User) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *User) SetId(v string) {
	o.Id = v
}

// GetDarkMode returns the DarkMode field value
func (o *User) GetDarkMode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DarkMode
}

// GetDarkModeOk returns a tuple with the DarkMode field value
// and a boolean to check if the value has been set.
func (o *User) GetDarkModeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DarkMode, true
}

// SetDarkMode sets field value
func (o *User) SetDarkMode(v bool) {
	o.DarkMode = v
}

// GetApiRefresh returns the ApiRefresh field value
func (o *User) GetApiRefresh() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ApiRefresh
}

// GetApiRefreshOk returns a tuple with the ApiRefresh field value
// and a boolean to check if the value has been set.
func (o *User) GetApiRefreshOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiRefresh, true
}

// SetApiRefresh sets field value
func (o *User) SetApiRefresh(v int32) {
	o.ApiRefresh = v
}

// GetIsAdmin returns the IsAdmin field value
func (o *User) GetIsAdmin() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAdmin
}

// GetIsAdminOk returns a tuple with the IsAdmin field value
// and a boolean to check if the value has been set.
func (o *User) GetIsAdminOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsAdmin, true
}

// SetIsAdmin sets field value
func (o *User) SetIsAdmin(v bool) {
	o.IsAdmin = v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o User) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["darkMode"] = o.DarkMode
	toSerialize["apiRefresh"] = o.ApiRefresh
	toSerialize["isAdmin"] = o.IsAdmin
	return toSerialize, nil
}

func (o *User) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"darkMode",
		"apiRefresh",
		"isAdmin",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUser := _User{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUser)

	if err != nil {
		return err
	}

	*o = User(varUser)

	return err
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


