/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SpaceReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpaceReq{}

// SpaceReq DOCSTRING
type SpaceReq struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type _SpaceReq SpaceReq

// NewSpaceReq instantiates a new SpaceReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpaceReq(name string, desc string) *SpaceReq {
	this := SpaceReq{}
	this.Name = name
	this.Desc = desc
	return &this
}

// NewSpaceReqWithDefaults instantiates a new SpaceReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpaceReqWithDefaults() *SpaceReq {
	this := SpaceReq{}
	return &this
}

// GetName returns the Name field value
func (o *SpaceReq) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SpaceReq) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SpaceReq) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *SpaceReq) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *SpaceReq) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *SpaceReq) SetDesc(v string) {
	o.Desc = v
}

func (o SpaceReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpaceReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	return toSerialize, nil
}

func (o *SpaceReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpaceReq := _SpaceReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpaceReq)

	if err != nil {
		return err
	}

	*o = SpaceReq(varSpaceReq)

	return err
}

type NullableSpaceReq struct {
	value *SpaceReq
	isSet bool
}

func (v NullableSpaceReq) Get() *SpaceReq {
	return v.value
}

func (v *NullableSpaceReq) Set(val *SpaceReq) {
	v.value = val
	v.isSet = true
}

func (v NullableSpaceReq) IsSet() bool {
	return v.isSet
}

func (v *NullableSpaceReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpaceReq(val *SpaceReq) *NullableSpaceReq {
	return &NullableSpaceReq{value: val, isSet: true}
}

func (v NullableSpaceReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpaceReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


