/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExtEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtEndpoint{}

// ExtEndpoint DOCSTRING
type ExtEndpoint struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
	Ip string `json:"ip"`
}

type _ExtEndpoint ExtEndpoint

// NewExtEndpoint instantiates a new ExtEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtEndpoint(name string, desc string, ip string) *ExtEndpoint {
	this := ExtEndpoint{}
	this.Name = name
	this.Desc = desc
	this.Ip = ip
	return &this
}

// NewExtEndpointWithDefaults instantiates a new ExtEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtEndpointWithDefaults() *ExtEndpoint {
	this := ExtEndpoint{}
	return &this
}

// GetName returns the Name field value
func (o *ExtEndpoint) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ExtEndpoint) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ExtEndpoint) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *ExtEndpoint) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *ExtEndpoint) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *ExtEndpoint) SetDesc(v string) {
	o.Desc = v
}

// GetIp returns the Ip field value
func (o *ExtEndpoint) GetIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ip
}

// GetIpOk returns a tuple with the Ip field value
// and a boolean to check if the value has been set.
func (o *ExtEndpoint) GetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ip, true
}

// SetIp sets field value
func (o *ExtEndpoint) SetIp(v string) {
	o.Ip = v
}

func (o ExtEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["ip"] = o.Ip
	return toSerialize, nil
}

func (o *ExtEndpoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"ip",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtEndpoint := _ExtEndpoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtEndpoint)

	if err != nil {
		return err
	}

	*o = ExtEndpoint(varExtEndpoint)

	return err
}

type NullableExtEndpoint struct {
	value *ExtEndpoint
	isSet bool
}

func (v NullableExtEndpoint) Get() *ExtEndpoint {
	return v.value
}

func (v *NullableExtEndpoint) Set(val *ExtEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableExtEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableExtEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtEndpoint(val *ExtEndpoint) *NullableExtEndpoint {
	return &NullableExtEndpoint{value: val, isSet: true}
}

func (v NullableExtEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


