/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExtNet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtNet{}

// ExtNet DOCSTRING
type ExtNet struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
	Cidr string `json:"cidr" validate:"regexp=x.x.x.x\\/x"`
	Subnets []ExtSubnet `json:"subnets"`
}

type _ExtNet ExtNet

// NewExtNet instantiates a new ExtNet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtNet(name string, desc string, cidr string, subnets []ExtSubnet) *ExtNet {
	this := ExtNet{}
	this.Name = name
	this.Desc = desc
	this.Cidr = cidr
	this.Subnets = subnets
	return &this
}

// NewExtNetWithDefaults instantiates a new ExtNet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtNetWithDefaults() *ExtNet {
	this := ExtNet{}
	return &this
}

// GetName returns the Name field value
func (o *ExtNet) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ExtNet) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ExtNet) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *ExtNet) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *ExtNet) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *ExtNet) SetDesc(v string) {
	o.Desc = v
}

// GetCidr returns the Cidr field value
func (o *ExtNet) GetCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value
// and a boolean to check if the value has been set.
func (o *ExtNet) GetCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cidr, true
}

// SetCidr sets field value
func (o *ExtNet) SetCidr(v string) {
	o.Cidr = v
}

// GetSubnets returns the Subnets field value
func (o *ExtNet) GetSubnets() []ExtSubnet {
	if o == nil {
		var ret []ExtSubnet
		return ret
	}

	return o.Subnets
}

// GetSubnetsOk returns a tuple with the Subnets field value
// and a boolean to check if the value has been set.
func (o *ExtNet) GetSubnetsOk() ([]ExtSubnet, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subnets, true
}

// SetSubnets sets field value
func (o *ExtNet) SetSubnets(v []ExtSubnet) {
	o.Subnets = v
}

func (o ExtNet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtNet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["cidr"] = o.Cidr
	toSerialize["subnets"] = o.Subnets
	return toSerialize, nil
}

func (o *ExtNet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"cidr",
		"subnets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtNet := _ExtNet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtNet)

	if err != nil {
		return err
	}

	*o = ExtNet(varExtNet)

	return err
}

type NullableExtNet struct {
	value *ExtNet
	isSet bool
}

func (v NullableExtNet) Get() *ExtNet {
	return v.value
}

func (v *NullableExtNet) Set(val *ExtNet) {
	v.value = val
	v.isSet = true
}

func (v NullableExtNet) IsSet() bool {
	return v.isSet
}

func (v *NullableExtNet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtNet(val *ExtNet) *NullableExtNet {
	return &NullableExtNet{value: val, isSet: true}
}

func (v NullableExtNet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtNet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


