/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReservationExpand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReservationExpand{}

// ReservationExpand DOCSTRING
type ReservationExpand struct {
	Id string `json:"id"`
	Space NullableString `json:"space,omitempty"`
	Block NullableString `json:"block,omitempty"`
	Cidr string `json:"cidr"`
	Desc NullableString `json:"desc,omitempty"`
	CreatedOn float32 `json:"createdOn"`
	CreatedBy string `json:"createdBy"`
	SettledOn NullableFloat32 `json:"settledOn,omitempty"`
	SettledBy NullableString `json:"settledBy,omitempty"`
	Status string `json:"status"`
	Tag map[string]interface{} `json:"tag,omitempty"`
}

type _ReservationExpand ReservationExpand

// NewReservationExpand instantiates a new ReservationExpand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReservationExpand(id string, cidr string, createdOn float32, createdBy string, status string) *ReservationExpand {
	this := ReservationExpand{}
	this.Id = id
	this.Cidr = cidr
	this.CreatedOn = createdOn
	this.CreatedBy = createdBy
	this.Status = status
	return &this
}

// NewReservationExpandWithDefaults instantiates a new ReservationExpand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReservationExpandWithDefaults() *ReservationExpand {
	this := ReservationExpand{}
	return &this
}

// GetId returns the Id field value
func (o *ReservationExpand) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ReservationExpand) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ReservationExpand) SetId(v string) {
	o.Id = v
}

// GetSpace returns the Space field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReservationExpand) GetSpace() string {
	if o == nil || IsNil(o.Space.Get()) {
		var ret string
		return ret
	}
	return *o.Space.Get()
}

// GetSpaceOk returns a tuple with the Space field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReservationExpand) GetSpaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Space.Get(), o.Space.IsSet()
}

// HasSpace returns a boolean if a field has been set.
func (o *ReservationExpand) HasSpace() bool {
	if o != nil && o.Space.IsSet() {
		return true
	}

	return false
}

// SetSpace gets a reference to the given NullableString and assigns it to the Space field.
func (o *ReservationExpand) SetSpace(v string) {
	o.Space.Set(&v)
}
// SetSpaceNil sets the value for Space to be an explicit nil
func (o *ReservationExpand) SetSpaceNil() {
	o.Space.Set(nil)
}

// UnsetSpace ensures that no value is present for Space, not even an explicit nil
func (o *ReservationExpand) UnsetSpace() {
	o.Space.Unset()
}

// GetBlock returns the Block field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReservationExpand) GetBlock() string {
	if o == nil || IsNil(o.Block.Get()) {
		var ret string
		return ret
	}
	return *o.Block.Get()
}

// GetBlockOk returns a tuple with the Block field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReservationExpand) GetBlockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Block.Get(), o.Block.IsSet()
}

// HasBlock returns a boolean if a field has been set.
func (o *ReservationExpand) HasBlock() bool {
	if o != nil && o.Block.IsSet() {
		return true
	}

	return false
}

// SetBlock gets a reference to the given NullableString and assigns it to the Block field.
func (o *ReservationExpand) SetBlock(v string) {
	o.Block.Set(&v)
}
// SetBlockNil sets the value for Block to be an explicit nil
func (o *ReservationExpand) SetBlockNil() {
	o.Block.Set(nil)
}

// UnsetBlock ensures that no value is present for Block, not even an explicit nil
func (o *ReservationExpand) UnsetBlock() {
	o.Block.Unset()
}

// GetCidr returns the Cidr field value
func (o *ReservationExpand) GetCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value
// and a boolean to check if the value has been set.
func (o *ReservationExpand) GetCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cidr, true
}

// SetCidr sets field value
func (o *ReservationExpand) SetCidr(v string) {
	o.Cidr = v
}

// GetDesc returns the Desc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReservationExpand) GetDesc() string {
	if o == nil || IsNil(o.Desc.Get()) {
		var ret string
		return ret
	}
	return *o.Desc.Get()
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReservationExpand) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Desc.Get(), o.Desc.IsSet()
}

// HasDesc returns a boolean if a field has been set.
func (o *ReservationExpand) HasDesc() bool {
	if o != nil && o.Desc.IsSet() {
		return true
	}

	return false
}

// SetDesc gets a reference to the given NullableString and assigns it to the Desc field.
func (o *ReservationExpand) SetDesc(v string) {
	o.Desc.Set(&v)
}
// SetDescNil sets the value for Desc to be an explicit nil
func (o *ReservationExpand) SetDescNil() {
	o.Desc.Set(nil)
}

// UnsetDesc ensures that no value is present for Desc, not even an explicit nil
func (o *ReservationExpand) UnsetDesc() {
	o.Desc.Unset()
}

// GetCreatedOn returns the CreatedOn field value
func (o *ReservationExpand) GetCreatedOn() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CreatedOn
}

// GetCreatedOnOk returns a tuple with the CreatedOn field value
// and a boolean to check if the value has been set.
func (o *ReservationExpand) GetCreatedOnOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedOn, true
}

// SetCreatedOn sets field value
func (o *ReservationExpand) SetCreatedOn(v float32) {
	o.CreatedOn = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *ReservationExpand) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *ReservationExpand) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *ReservationExpand) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetSettledOn returns the SettledOn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReservationExpand) GetSettledOn() float32 {
	if o == nil || IsNil(o.SettledOn.Get()) {
		var ret float32
		return ret
	}
	return *o.SettledOn.Get()
}

// GetSettledOnOk returns a tuple with the SettledOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReservationExpand) GetSettledOnOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SettledOn.Get(), o.SettledOn.IsSet()
}

// HasSettledOn returns a boolean if a field has been set.
func (o *ReservationExpand) HasSettledOn() bool {
	if o != nil && o.SettledOn.IsSet() {
		return true
	}

	return false
}

// SetSettledOn gets a reference to the given NullableFloat32 and assigns it to the SettledOn field.
func (o *ReservationExpand) SetSettledOn(v float32) {
	o.SettledOn.Set(&v)
}
// SetSettledOnNil sets the value for SettledOn to be an explicit nil
func (o *ReservationExpand) SetSettledOnNil() {
	o.SettledOn.Set(nil)
}

// UnsetSettledOn ensures that no value is present for SettledOn, not even an explicit nil
func (o *ReservationExpand) UnsetSettledOn() {
	o.SettledOn.Unset()
}

// GetSettledBy returns the SettledBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReservationExpand) GetSettledBy() string {
	if o == nil || IsNil(o.SettledBy.Get()) {
		var ret string
		return ret
	}
	return *o.SettledBy.Get()
}

// GetSettledByOk returns a tuple with the SettledBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReservationExpand) GetSettledByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SettledBy.Get(), o.SettledBy.IsSet()
}

// HasSettledBy returns a boolean if a field has been set.
func (o *ReservationExpand) HasSettledBy() bool {
	if o != nil && o.SettledBy.IsSet() {
		return true
	}

	return false
}

// SetSettledBy gets a reference to the given NullableString and assigns it to the SettledBy field.
func (o *ReservationExpand) SetSettledBy(v string) {
	o.SettledBy.Set(&v)
}
// SetSettledByNil sets the value for SettledBy to be an explicit nil
func (o *ReservationExpand) SetSettledByNil() {
	o.SettledBy.Set(nil)
}

// UnsetSettledBy ensures that no value is present for SettledBy, not even an explicit nil
func (o *ReservationExpand) UnsetSettledBy() {
	o.SettledBy.Unset()
}

// GetStatus returns the Status field value
func (o *ReservationExpand) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ReservationExpand) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ReservationExpand) SetStatus(v string) {
	o.Status = v
}

// GetTag returns the Tag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReservationExpand) GetTag() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReservationExpand) GetTagOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tag) {
		return map[string]interface{}{}, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *ReservationExpand) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given map[string]interface{} and assigns it to the Tag field.
func (o *ReservationExpand) SetTag(v map[string]interface{}) {
	o.Tag = v
}

func (o ReservationExpand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReservationExpand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.Space.IsSet() {
		toSerialize["space"] = o.Space.Get()
	}
	if o.Block.IsSet() {
		toSerialize["block"] = o.Block.Get()
	}
	toSerialize["cidr"] = o.Cidr
	if o.Desc.IsSet() {
		toSerialize["desc"] = o.Desc.Get()
	}
	toSerialize["createdOn"] = o.CreatedOn
	toSerialize["createdBy"] = o.CreatedBy
	if o.SettledOn.IsSet() {
		toSerialize["settledOn"] = o.SettledOn.Get()
	}
	if o.SettledBy.IsSet() {
		toSerialize["settledBy"] = o.SettledBy.Get()
	}
	toSerialize["status"] = o.Status
	if o.Tag != nil {
		toSerialize["tag"] = o.Tag
	}
	return toSerialize, nil
}

func (o *ReservationExpand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"cidr",
		"createdOn",
		"createdBy",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReservationExpand := _ReservationExpand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReservationExpand)

	if err != nil {
		return err
	}

	*o = ReservationExpand(varReservationExpand)

	return err
}

type NullableReservationExpand struct {
	value *ReservationExpand
	isSet bool
}

func (v NullableReservationExpand) Get() *ReservationExpand {
	return v.value
}

func (v *NullableReservationExpand) Set(val *ReservationExpand) {
	v.value = val
	v.isSet = true
}

func (v NullableReservationExpand) IsSet() bool {
	return v.isSet
}

func (v *NullableReservationExpand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReservationExpand(val *ReservationExpand) *NullableReservationExpand {
	return &NullableReservationExpand{value: val, isSet: true}
}

func (v NullableReservationExpand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReservationExpand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


