/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExtEndpointReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtEndpointReq{}

// ExtEndpointReq DOCSTRING
type ExtEndpointReq struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
	Ip NullableString `json:"ip" validate:"regexp=x.x.x.x"`
}

type _ExtEndpointReq ExtEndpointReq

// NewExtEndpointReq instantiates a new ExtEndpointReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtEndpointReq(name string, desc string, ip NullableString) *ExtEndpointReq {
	this := ExtEndpointReq{}
	this.Name = name
	this.Desc = desc
	this.Ip = ip
	return &this
}

// NewExtEndpointReqWithDefaults instantiates a new ExtEndpointReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtEndpointReqWithDefaults() *ExtEndpointReq {
	this := ExtEndpointReq{}
	return &this
}

// GetName returns the Name field value
func (o *ExtEndpointReq) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ExtEndpointReq) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ExtEndpointReq) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *ExtEndpointReq) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *ExtEndpointReq) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *ExtEndpointReq) SetDesc(v string) {
	o.Desc = v
}

// GetIp returns the Ip field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ExtEndpointReq) GetIp() string {
	if o == nil || o.Ip.Get() == nil {
		var ret string
		return ret
	}

	return *o.Ip.Get()
}

// GetIpOk returns a tuple with the Ip field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExtEndpointReq) GetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ip.Get(), o.Ip.IsSet()
}

// SetIp sets field value
func (o *ExtEndpointReq) SetIp(v string) {
	o.Ip.Set(&v)
}

func (o ExtEndpointReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtEndpointReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["ip"] = o.Ip.Get()
	return toSerialize, nil
}

func (o *ExtEndpointReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"ip",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtEndpointReq := _ExtEndpointReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtEndpointReq)

	if err != nil {
		return err
	}

	*o = ExtEndpointReq(varExtEndpointReq)

	return err
}

type NullableExtEndpointReq struct {
	value *ExtEndpointReq
	isSet bool
}

func (v NullableExtEndpointReq) Get() *ExtEndpointReq {
	return v.value
}

func (v *NullableExtEndpointReq) Set(val *ExtEndpointReq) {
	v.value = val
	v.isSet = true
}

func (v NullableExtEndpointReq) IsSet() bool {
	return v.isSet
}

func (v *NullableExtEndpointReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtEndpointReq(val *ExtEndpointReq) *NullableExtEndpointReq {
	return &NullableExtEndpointReq{value: val, isSet: true}
}

func (v NullableExtEndpointReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtEndpointReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


