/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CIDRCheckRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CIDRCheckRes{}

// CIDRCheckRes DOCSTRING
type CIDRCheckRes struct {
	Name string `json:"name"`
	Id string `json:"id"`
	ResourceGroup string `json:"resource_group"`
	SubscriptionId string `json:"subscription_id"`
	TenantId string `json:"tenant_id"`
	Prefixes []string `json:"prefixes"`
	Containers []CIDRContainer `json:"containers"`
}

type _CIDRCheckRes CIDRCheckRes

// NewCIDRCheckRes instantiates a new CIDRCheckRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCIDRCheckRes(name string, id string, resourceGroup string, subscriptionId string, tenantId string, prefixes []string, containers []CIDRContainer) *CIDRCheckRes {
	this := CIDRCheckRes{}
	this.Name = name
	this.Id = id
	this.ResourceGroup = resourceGroup
	this.SubscriptionId = subscriptionId
	this.TenantId = tenantId
	this.Prefixes = prefixes
	this.Containers = containers
	return &this
}

// NewCIDRCheckResWithDefaults instantiates a new CIDRCheckRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCIDRCheckResWithDefaults() *CIDRCheckRes {
	this := CIDRCheckRes{}
	return &this
}

// GetName returns the Name field value
func (o *CIDRCheckRes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CIDRCheckRes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CIDRCheckRes) SetName(v string) {
	o.Name = v
}

// GetId returns the Id field value
func (o *CIDRCheckRes) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CIDRCheckRes) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CIDRCheckRes) SetId(v string) {
	o.Id = v
}

// GetResourceGroup returns the ResourceGroup field value
func (o *CIDRCheckRes) GetResourceGroup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceGroup
}

// GetResourceGroupOk returns a tuple with the ResourceGroup field value
// and a boolean to check if the value has been set.
func (o *CIDRCheckRes) GetResourceGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceGroup, true
}

// SetResourceGroup sets field value
func (o *CIDRCheckRes) SetResourceGroup(v string) {
	o.ResourceGroup = v
}

// GetSubscriptionId returns the SubscriptionId field value
func (o *CIDRCheckRes) GetSubscriptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value
// and a boolean to check if the value has been set.
func (o *CIDRCheckRes) GetSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionId, true
}

// SetSubscriptionId sets field value
func (o *CIDRCheckRes) SetSubscriptionId(v string) {
	o.SubscriptionId = v
}

// GetTenantId returns the TenantId field value
func (o *CIDRCheckRes) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *CIDRCheckRes) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *CIDRCheckRes) SetTenantId(v string) {
	o.TenantId = v
}

// GetPrefixes returns the Prefixes field value
func (o *CIDRCheckRes) GetPrefixes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Prefixes
}

// GetPrefixesOk returns a tuple with the Prefixes field value
// and a boolean to check if the value has been set.
func (o *CIDRCheckRes) GetPrefixesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prefixes, true
}

// SetPrefixes sets field value
func (o *CIDRCheckRes) SetPrefixes(v []string) {
	o.Prefixes = v
}

// GetContainers returns the Containers field value
func (o *CIDRCheckRes) GetContainers() []CIDRContainer {
	if o == nil {
		var ret []CIDRContainer
		return ret
	}

	return o.Containers
}

// GetContainersOk returns a tuple with the Containers field value
// and a boolean to check if the value has been set.
func (o *CIDRCheckRes) GetContainersOk() ([]CIDRContainer, bool) {
	if o == nil {
		return nil, false
	}
	return o.Containers, true
}

// SetContainers sets field value
func (o *CIDRCheckRes) SetContainers(v []CIDRContainer) {
	o.Containers = v
}

func (o CIDRCheckRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CIDRCheckRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["id"] = o.Id
	toSerialize["resource_group"] = o.ResourceGroup
	toSerialize["subscription_id"] = o.SubscriptionId
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["prefixes"] = o.Prefixes
	toSerialize["containers"] = o.Containers
	return toSerialize, nil
}

func (o *CIDRCheckRes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"id",
		"resource_group",
		"subscription_id",
		"tenant_id",
		"prefixes",
		"containers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCIDRCheckRes := _CIDRCheckRes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCIDRCheckRes)

	if err != nil {
		return err
	}

	*o = CIDRCheckRes(varCIDRCheckRes)

	return err
}

type NullableCIDRCheckRes struct {
	value *CIDRCheckRes
	isSet bool
}

func (v NullableCIDRCheckRes) Get() *CIDRCheckRes {
	return v.value
}

func (v *NullableCIDRCheckRes) Set(val *CIDRCheckRes) {
	v.value = val
	v.isSet = true
}

func (v NullableCIDRCheckRes) IsSet() bool {
	return v.isSet
}

func (v *NullableCIDRCheckRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCIDRCheckRes(val *CIDRCheckRes) *NullableCIDRCheckRes {
	return &NullableCIDRCheckRes{value: val, isSet: true}
}

func (v NullableCIDRCheckRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCIDRCheckRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


