/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CIDRCheckReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CIDRCheckReq{}

// CIDRCheckReq DOCSTRING
type CIDRCheckReq struct {
	Cidr string `json:"cidr" validate:"regexp=x.x.x.x\\/x"`
}

type _CIDRCheckReq CIDRCheckReq

// NewCIDRCheckReq instantiates a new CIDRCheckReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCIDRCheckReq(cidr string) *CIDRCheckReq {
	this := CIDRCheckReq{}
	this.Cidr = cidr
	return &this
}

// NewCIDRCheckReqWithDefaults instantiates a new CIDRCheckReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCIDRCheckReqWithDefaults() *CIDRCheckReq {
	this := CIDRCheckReq{}
	return &this
}

// GetCidr returns the Cidr field value
func (o *CIDRCheckReq) GetCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value
// and a boolean to check if the value has been set.
func (o *CIDRCheckReq) GetCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cidr, true
}

// SetCidr sets field value
func (o *CIDRCheckReq) SetCidr(v string) {
	o.Cidr = v
}

func (o CIDRCheckReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CIDRCheckReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cidr"] = o.Cidr
	return toSerialize, nil
}

func (o *CIDRCheckReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cidr",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCIDRCheckReq := _CIDRCheckReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCIDRCheckReq)

	if err != nil {
		return err
	}

	*o = CIDRCheckReq(varCIDRCheckReq)

	return err
}

type NullableCIDRCheckReq struct {
	value *CIDRCheckReq
	isSet bool
}

func (v NullableCIDRCheckReq) Get() *CIDRCheckReq {
	return v.value
}

func (v *NullableCIDRCheckReq) Set(val *CIDRCheckReq) {
	v.value = val
	v.isSet = true
}

func (v NullableCIDRCheckReq) IsSet() bool {
	return v.isSet
}

func (v *NullableCIDRCheckReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCIDRCheckReq(val *CIDRCheckReq) *NullableCIDRCheckReq {
	return &NullableCIDRCheckReq{value: val, isSet: true}
}

func (v NullableCIDRCheckReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCIDRCheckReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


