/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SpaceBasic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpaceBasic{}

// SpaceBasic DOCSTRING
type SpaceBasic struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
	Blocks []BlockBasic `json:"blocks"`
}

type _SpaceBasic SpaceBasic

// NewSpaceBasic instantiates a new SpaceBasic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpaceBasic(name string, desc string, blocks []BlockBasic) *SpaceBasic {
	this := SpaceBasic{}
	this.Name = name
	this.Desc = desc
	this.Blocks = blocks
	return &this
}

// NewSpaceBasicWithDefaults instantiates a new SpaceBasic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpaceBasicWithDefaults() *SpaceBasic {
	this := SpaceBasic{}
	return &this
}

// GetName returns the Name field value
func (o *SpaceBasic) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SpaceBasic) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SpaceBasic) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *SpaceBasic) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *SpaceBasic) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *SpaceBasic) SetDesc(v string) {
	o.Desc = v
}

// GetBlocks returns the Blocks field value
func (o *SpaceBasic) GetBlocks() []BlockBasic {
	if o == nil {
		var ret []BlockBasic
		return ret
	}

	return o.Blocks
}

// GetBlocksOk returns a tuple with the Blocks field value
// and a boolean to check if the value has been set.
func (o *SpaceBasic) GetBlocksOk() ([]BlockBasic, bool) {
	if o == nil {
		return nil, false
	}
	return o.Blocks, true
}

// SetBlocks sets field value
func (o *SpaceBasic) SetBlocks(v []BlockBasic) {
	o.Blocks = v
}

func (o SpaceBasic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpaceBasic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["blocks"] = o.Blocks
	return toSerialize, nil
}

func (o *SpaceBasic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"blocks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpaceBasic := _SpaceBasic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpaceBasic)

	if err != nil {
		return err
	}

	*o = SpaceBasic(varSpaceBasic)

	return err
}

type NullableSpaceBasic struct {
	value *SpaceBasic
	isSet bool
}

func (v NullableSpaceBasic) Get() *SpaceBasic {
	return v.value
}

func (v *NullableSpaceBasic) Set(val *SpaceBasic) {
	v.value = val
	v.isSet = true
}

func (v NullableSpaceBasic) IsSet() bool {
	return v.isSet
}

func (v *NullableSpaceBasic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpaceBasic(val *SpaceBasic) *NullableSpaceBasic {
	return &NullableSpaceBasic{value: val, isSet: true}
}

func (v NullableSpaceBasic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpaceBasic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


