/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BlockExpand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlockExpand{}

// BlockExpand DOCSTRING
type BlockExpand struct {
	Name string `json:"name"`
	Cidr string `json:"cidr"`
	Vnets []VNetExpand `json:"vnets"`
	Externals []ExtNet `json:"externals"`
	Resv []Reservation `json:"resv"`
}

type _BlockExpand BlockExpand

// NewBlockExpand instantiates a new BlockExpand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockExpand(name string, cidr string, vnets []VNetExpand, externals []ExtNet, resv []Reservation) *BlockExpand {
	this := BlockExpand{}
	this.Name = name
	this.Cidr = cidr
	this.Vnets = vnets
	this.Externals = externals
	this.Resv = resv
	return &this
}

// NewBlockExpandWithDefaults instantiates a new BlockExpand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockExpandWithDefaults() *BlockExpand {
	this := BlockExpand{}
	return &this
}

// GetName returns the Name field value
func (o *BlockExpand) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BlockExpand) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BlockExpand) SetName(v string) {
	o.Name = v
}

// GetCidr returns the Cidr field value
func (o *BlockExpand) GetCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value
// and a boolean to check if the value has been set.
func (o *BlockExpand) GetCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cidr, true
}

// SetCidr sets field value
func (o *BlockExpand) SetCidr(v string) {
	o.Cidr = v
}

// GetVnets returns the Vnets field value
func (o *BlockExpand) GetVnets() []VNetExpand {
	if o == nil {
		var ret []VNetExpand
		return ret
	}

	return o.Vnets
}

// GetVnetsOk returns a tuple with the Vnets field value
// and a boolean to check if the value has been set.
func (o *BlockExpand) GetVnetsOk() ([]VNetExpand, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vnets, true
}

// SetVnets sets field value
func (o *BlockExpand) SetVnets(v []VNetExpand) {
	o.Vnets = v
}

// GetExternals returns the Externals field value
func (o *BlockExpand) GetExternals() []ExtNet {
	if o == nil {
		var ret []ExtNet
		return ret
	}

	return o.Externals
}

// GetExternalsOk returns a tuple with the Externals field value
// and a boolean to check if the value has been set.
func (o *BlockExpand) GetExternalsOk() ([]ExtNet, bool) {
	if o == nil {
		return nil, false
	}
	return o.Externals, true
}

// SetExternals sets field value
func (o *BlockExpand) SetExternals(v []ExtNet) {
	o.Externals = v
}

// GetResv returns the Resv field value
func (o *BlockExpand) GetResv() []Reservation {
	if o == nil {
		var ret []Reservation
		return ret
	}

	return o.Resv
}

// GetResvOk returns a tuple with the Resv field value
// and a boolean to check if the value has been set.
func (o *BlockExpand) GetResvOk() ([]Reservation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Resv, true
}

// SetResv sets field value
func (o *BlockExpand) SetResv(v []Reservation) {
	o.Resv = v
}

func (o BlockExpand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlockExpand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["cidr"] = o.Cidr
	toSerialize["vnets"] = o.Vnets
	toSerialize["externals"] = o.Externals
	toSerialize["resv"] = o.Resv
	return toSerialize, nil
}

func (o *BlockExpand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"cidr",
		"vnets",
		"externals",
		"resv",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlockExpand := _BlockExpand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBlockExpand)

	if err != nil {
		return err
	}

	*o = BlockExpand(varBlockExpand)

	return err
}

type NullableBlockExpand struct {
	value *BlockExpand
	isSet bool
}

func (v NullableBlockExpand) Get() *BlockExpand {
	return v.value
}

func (v *NullableBlockExpand) Set(val *BlockExpand) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockExpand) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockExpand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockExpand(val *BlockExpand) *NullableBlockExpand {
	return &NullableBlockExpand{value: val, isSet: true}
}

func (v NullableBlockExpand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockExpand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


