/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VNetExpandUtil type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VNetExpandUtil{}

// VNetExpandUtil DOCSTRING
type VNetExpandUtil struct {
	Name string `json:"name"`
	Id string `json:"id"`
	Prefixes []string `json:"prefixes"`
	Subnets []SubnetUtil `json:"subnets"`
	ResourceGroup string `json:"resource_group"`
	SubscriptionId string `json:"subscription_id"`
	TenantId string `json:"tenant_id"`
	Size int32 `json:"size"`
	Used int32 `json:"used"`
}

type _VNetExpandUtil VNetExpandUtil

// NewVNetExpandUtil instantiates a new VNetExpandUtil object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVNetExpandUtil(name string, id string, prefixes []string, subnets []SubnetUtil, resourceGroup string, subscriptionId string, tenantId string, size int32, used int32) *VNetExpandUtil {
	this := VNetExpandUtil{}
	this.Name = name
	this.Id = id
	this.Prefixes = prefixes
	this.Subnets = subnets
	this.ResourceGroup = resourceGroup
	this.SubscriptionId = subscriptionId
	this.TenantId = tenantId
	this.Size = size
	this.Used = used
	return &this
}

// NewVNetExpandUtilWithDefaults instantiates a new VNetExpandUtil object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVNetExpandUtilWithDefaults() *VNetExpandUtil {
	this := VNetExpandUtil{}
	return &this
}

// GetName returns the Name field value
func (o *VNetExpandUtil) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VNetExpandUtil) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VNetExpandUtil) SetName(v string) {
	o.Name = v
}

// GetId returns the Id field value
func (o *VNetExpandUtil) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VNetExpandUtil) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VNetExpandUtil) SetId(v string) {
	o.Id = v
}

// GetPrefixes returns the Prefixes field value
func (o *VNetExpandUtil) GetPrefixes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Prefixes
}

// GetPrefixesOk returns a tuple with the Prefixes field value
// and a boolean to check if the value has been set.
func (o *VNetExpandUtil) GetPrefixesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prefixes, true
}

// SetPrefixes sets field value
func (o *VNetExpandUtil) SetPrefixes(v []string) {
	o.Prefixes = v
}

// GetSubnets returns the Subnets field value
func (o *VNetExpandUtil) GetSubnets() []SubnetUtil {
	if o == nil {
		var ret []SubnetUtil
		return ret
	}

	return o.Subnets
}

// GetSubnetsOk returns a tuple with the Subnets field value
// and a boolean to check if the value has been set.
func (o *VNetExpandUtil) GetSubnetsOk() ([]SubnetUtil, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subnets, true
}

// SetSubnets sets field value
func (o *VNetExpandUtil) SetSubnets(v []SubnetUtil) {
	o.Subnets = v
}

// GetResourceGroup returns the ResourceGroup field value
func (o *VNetExpandUtil) GetResourceGroup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceGroup
}

// GetResourceGroupOk returns a tuple with the ResourceGroup field value
// and a boolean to check if the value has been set.
func (o *VNetExpandUtil) GetResourceGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceGroup, true
}

// SetResourceGroup sets field value
func (o *VNetExpandUtil) SetResourceGroup(v string) {
	o.ResourceGroup = v
}

// GetSubscriptionId returns the SubscriptionId field value
func (o *VNetExpandUtil) GetSubscriptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value
// and a boolean to check if the value has been set.
func (o *VNetExpandUtil) GetSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionId, true
}

// SetSubscriptionId sets field value
func (o *VNetExpandUtil) SetSubscriptionId(v string) {
	o.SubscriptionId = v
}

// GetTenantId returns the TenantId field value
func (o *VNetExpandUtil) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *VNetExpandUtil) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *VNetExpandUtil) SetTenantId(v string) {
	o.TenantId = v
}

// GetSize returns the Size field value
func (o *VNetExpandUtil) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *VNetExpandUtil) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *VNetExpandUtil) SetSize(v int32) {
	o.Size = v
}

// GetUsed returns the Used field value
func (o *VNetExpandUtil) GetUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *VNetExpandUtil) GetUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *VNetExpandUtil) SetUsed(v int32) {
	o.Used = v
}

func (o VNetExpandUtil) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VNetExpandUtil) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["id"] = o.Id
	toSerialize["prefixes"] = o.Prefixes
	toSerialize["subnets"] = o.Subnets
	toSerialize["resource_group"] = o.ResourceGroup
	toSerialize["subscription_id"] = o.SubscriptionId
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["size"] = o.Size
	toSerialize["used"] = o.Used
	return toSerialize, nil
}

func (o *VNetExpandUtil) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"id",
		"prefixes",
		"subnets",
		"resource_group",
		"subscription_id",
		"tenant_id",
		"size",
		"used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVNetExpandUtil := _VNetExpandUtil{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVNetExpandUtil)

	if err != nil {
		return err
	}

	*o = VNetExpandUtil(varVNetExpandUtil)

	return err
}

type NullableVNetExpandUtil struct {
	value *VNetExpandUtil
	isSet bool
}

func (v NullableVNetExpandUtil) Get() *VNetExpandUtil {
	return v.value
}

func (v *NullableVNetExpandUtil) Set(val *VNetExpandUtil) {
	v.value = val
	v.isSet = true
}

func (v NullableVNetExpandUtil) IsSet() bool {
	return v.isSet
}

func (v *NullableVNetExpandUtil) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVNetExpandUtil(val *VNetExpandUtil) *NullableVNetExpandUtil {
	return &NullableVNetExpandUtil{value: val, isSet: true}
}

func (v NullableVNetExpandUtil) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVNetExpandUtil) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


