/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BlockExpandUtil type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlockExpandUtil{}

// BlockExpandUtil DOCSTRING
type BlockExpandUtil struct {
	Name string `json:"name"`
	Cidr string `json:"cidr"`
	Vnets []VNetExpandUtil `json:"vnets"`
	Externals []ExtNet `json:"externals"`
	Resv []Reservation `json:"resv"`
	Size int32 `json:"size"`
	Used int32 `json:"used"`
}

type _BlockExpandUtil BlockExpandUtil

// NewBlockExpandUtil instantiates a new BlockExpandUtil object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockExpandUtil(name string, cidr string, vnets []VNetExpandUtil, externals []ExtNet, resv []Reservation, size int32, used int32) *BlockExpandUtil {
	this := BlockExpandUtil{}
	this.Name = name
	this.Cidr = cidr
	this.Vnets = vnets
	this.Externals = externals
	this.Resv = resv
	this.Size = size
	this.Used = used
	return &this
}

// NewBlockExpandUtilWithDefaults instantiates a new BlockExpandUtil object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockExpandUtilWithDefaults() *BlockExpandUtil {
	this := BlockExpandUtil{}
	return &this
}

// GetName returns the Name field value
func (o *BlockExpandUtil) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BlockExpandUtil) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BlockExpandUtil) SetName(v string) {
	o.Name = v
}

// GetCidr returns the Cidr field value
func (o *BlockExpandUtil) GetCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value
// and a boolean to check if the value has been set.
func (o *BlockExpandUtil) GetCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cidr, true
}

// SetCidr sets field value
func (o *BlockExpandUtil) SetCidr(v string) {
	o.Cidr = v
}

// GetVnets returns the Vnets field value
func (o *BlockExpandUtil) GetVnets() []VNetExpandUtil {
	if o == nil {
		var ret []VNetExpandUtil
		return ret
	}

	return o.Vnets
}

// GetVnetsOk returns a tuple with the Vnets field value
// and a boolean to check if the value has been set.
func (o *BlockExpandUtil) GetVnetsOk() ([]VNetExpandUtil, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vnets, true
}

// SetVnets sets field value
func (o *BlockExpandUtil) SetVnets(v []VNetExpandUtil) {
	o.Vnets = v
}

// GetExternals returns the Externals field value
func (o *BlockExpandUtil) GetExternals() []ExtNet {
	if o == nil {
		var ret []ExtNet
		return ret
	}

	return o.Externals
}

// GetExternalsOk returns a tuple with the Externals field value
// and a boolean to check if the value has been set.
func (o *BlockExpandUtil) GetExternalsOk() ([]ExtNet, bool) {
	if o == nil {
		return nil, false
	}
	return o.Externals, true
}

// SetExternals sets field value
func (o *BlockExpandUtil) SetExternals(v []ExtNet) {
	o.Externals = v
}

// GetResv returns the Resv field value
func (o *BlockExpandUtil) GetResv() []Reservation {
	if o == nil {
		var ret []Reservation
		return ret
	}

	return o.Resv
}

// GetResvOk returns a tuple with the Resv field value
// and a boolean to check if the value has been set.
func (o *BlockExpandUtil) GetResvOk() ([]Reservation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Resv, true
}

// SetResv sets field value
func (o *BlockExpandUtil) SetResv(v []Reservation) {
	o.Resv = v
}

// GetSize returns the Size field value
func (o *BlockExpandUtil) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *BlockExpandUtil) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *BlockExpandUtil) SetSize(v int32) {
	o.Size = v
}

// GetUsed returns the Used field value
func (o *BlockExpandUtil) GetUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *BlockExpandUtil) GetUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *BlockExpandUtil) SetUsed(v int32) {
	o.Used = v
}

func (o BlockExpandUtil) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlockExpandUtil) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["cidr"] = o.Cidr
	toSerialize["vnets"] = o.Vnets
	toSerialize["externals"] = o.Externals
	toSerialize["resv"] = o.Resv
	toSerialize["size"] = o.Size
	toSerialize["used"] = o.Used
	return toSerialize, nil
}

func (o *BlockExpandUtil) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"cidr",
		"vnets",
		"externals",
		"resv",
		"size",
		"used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlockExpandUtil := _BlockExpandUtil{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBlockExpandUtil)

	if err != nil {
		return err
	}

	*o = BlockExpandUtil(varBlockExpandUtil)

	return err
}

type NullableBlockExpandUtil struct {
	value *BlockExpandUtil
	isSet bool
}

func (v NullableBlockExpandUtil) Get() *BlockExpandUtil {
	return v.value
}

func (v *NullableBlockExpandUtil) Set(val *BlockExpandUtil) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockExpandUtil) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockExpandUtil) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockExpandUtil(val *BlockExpandUtil) *NullableBlockExpandUtil {
	return &NullableBlockExpandUtil{value: val, isSet: true}
}

func (v NullableBlockExpandUtil) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockExpandUtil) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


