/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// ResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet struct for ResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet
type ResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet struct {
	ArrayOfNetwork *[]Network
	ArrayOfNetworkExpand *[]NetworkExpand
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ArrayOfNetwork
	err = json.Unmarshal(data, &dst.ArrayOfNetwork);
	if err == nil {
		jsonArrayOfNetwork, _ := json.Marshal(dst.ArrayOfNetwork)
		if string(jsonArrayOfNetwork) == "{}" { // empty struct
			dst.ArrayOfNetwork = nil
		} else {
			return nil // data stored in dst.ArrayOfNetwork, return on the first match
		}
	} else {
		dst.ArrayOfNetwork = nil
	}

	// try to unmarshal JSON data into ArrayOfNetworkExpand
	err = json.Unmarshal(data, &dst.ArrayOfNetworkExpand);
	if err == nil {
		jsonArrayOfNetworkExpand, _ := json.Marshal(dst.ArrayOfNetworkExpand)
		if string(jsonArrayOfNetworkExpand) == "{}" { // empty struct
			dst.ArrayOfNetworkExpand = nil
		} else {
			return nil // data stored in dst.ArrayOfNetworkExpand, return on the first match
		}
	} else {
		dst.ArrayOfNetworkExpand = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *ResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet) MarshalJSON() ([]byte, error) {
	if src.ArrayOfNetwork != nil {
		return json.Marshal(&src.ArrayOfNetwork)
	}

	if src.ArrayOfNetworkExpand != nil {
		return json.Marshal(&src.ArrayOfNetworkExpand)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet struct {
	value *ResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet
	isSet bool
}

func (v NullableResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet) Get() *ResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet {
	return v.value
}

func (v *NullableResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet) Set(val *ResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet(val *ResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet) *NullableResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet {
	return &NullableResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet{value: val, isSet: true}
}

func (v NullableResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseGetBlockNetsApiSpacesSpaceBlocksBlockNetworksGet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


