/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubnetCIDRReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubnetCIDRReq{}

// SubnetCIDRReq DOCSTRING
type SubnetCIDRReq struct {
	VnetId string `json:"vnet_id"`
	Size int32 `json:"size"`
	ReverseSearch NullableBool `json:"reverse_search,omitempty"`
	SmallestCidr NullableBool `json:"smallest_cidr,omitempty"`
}

type _SubnetCIDRReq SubnetCIDRReq

// NewSubnetCIDRReq instantiates a new SubnetCIDRReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnetCIDRReq(vnetId string, size int32) *SubnetCIDRReq {
	this := SubnetCIDRReq{}
	this.VnetId = vnetId
	this.Size = size
	return &this
}

// NewSubnetCIDRReqWithDefaults instantiates a new SubnetCIDRReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetCIDRReqWithDefaults() *SubnetCIDRReq {
	this := SubnetCIDRReq{}
	return &this
}

// GetVnetId returns the VnetId field value
func (o *SubnetCIDRReq) GetVnetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VnetId
}

// GetVnetIdOk returns a tuple with the VnetId field value
// and a boolean to check if the value has been set.
func (o *SubnetCIDRReq) GetVnetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VnetId, true
}

// SetVnetId sets field value
func (o *SubnetCIDRReq) SetVnetId(v string) {
	o.VnetId = v
}

// GetSize returns the Size field value
func (o *SubnetCIDRReq) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *SubnetCIDRReq) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *SubnetCIDRReq) SetSize(v int32) {
	o.Size = v
}

// GetReverseSearch returns the ReverseSearch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetCIDRReq) GetReverseSearch() bool {
	if o == nil || IsNil(o.ReverseSearch.Get()) {
		var ret bool
		return ret
	}
	return *o.ReverseSearch.Get()
}

// GetReverseSearchOk returns a tuple with the ReverseSearch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetCIDRReq) GetReverseSearchOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReverseSearch.Get(), o.ReverseSearch.IsSet()
}

// HasReverseSearch returns a boolean if a field has been set.
func (o *SubnetCIDRReq) HasReverseSearch() bool {
	if o != nil && o.ReverseSearch.IsSet() {
		return true
	}

	return false
}

// SetReverseSearch gets a reference to the given NullableBool and assigns it to the ReverseSearch field.
func (o *SubnetCIDRReq) SetReverseSearch(v bool) {
	o.ReverseSearch.Set(&v)
}
// SetReverseSearchNil sets the value for ReverseSearch to be an explicit nil
func (o *SubnetCIDRReq) SetReverseSearchNil() {
	o.ReverseSearch.Set(nil)
}

// UnsetReverseSearch ensures that no value is present for ReverseSearch, not even an explicit nil
func (o *SubnetCIDRReq) UnsetReverseSearch() {
	o.ReverseSearch.Unset()
}

// GetSmallestCidr returns the SmallestCidr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetCIDRReq) GetSmallestCidr() bool {
	if o == nil || IsNil(o.SmallestCidr.Get()) {
		var ret bool
		return ret
	}
	return *o.SmallestCidr.Get()
}

// GetSmallestCidrOk returns a tuple with the SmallestCidr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetCIDRReq) GetSmallestCidrOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SmallestCidr.Get(), o.SmallestCidr.IsSet()
}

// HasSmallestCidr returns a boolean if a field has been set.
func (o *SubnetCIDRReq) HasSmallestCidr() bool {
	if o != nil && o.SmallestCidr.IsSet() {
		return true
	}

	return false
}

// SetSmallestCidr gets a reference to the given NullableBool and assigns it to the SmallestCidr field.
func (o *SubnetCIDRReq) SetSmallestCidr(v bool) {
	o.SmallestCidr.Set(&v)
}
// SetSmallestCidrNil sets the value for SmallestCidr to be an explicit nil
func (o *SubnetCIDRReq) SetSmallestCidrNil() {
	o.SmallestCidr.Set(nil)
}

// UnsetSmallestCidr ensures that no value is present for SmallestCidr, not even an explicit nil
func (o *SubnetCIDRReq) UnsetSmallestCidr() {
	o.SmallestCidr.Unset()
}

func (o SubnetCIDRReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubnetCIDRReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vnet_id"] = o.VnetId
	toSerialize["size"] = o.Size
	if o.ReverseSearch.IsSet() {
		toSerialize["reverse_search"] = o.ReverseSearch.Get()
	}
	if o.SmallestCidr.IsSet() {
		toSerialize["smallest_cidr"] = o.SmallestCidr.Get()
	}
	return toSerialize, nil
}

func (o *SubnetCIDRReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vnet_id",
		"size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubnetCIDRReq := _SubnetCIDRReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubnetCIDRReq)

	if err != nil {
		return err
	}

	*o = SubnetCIDRReq(varSubnetCIDRReq)

	return err
}

type NullableSubnetCIDRReq struct {
	value *SubnetCIDRReq
	isSet bool
}

func (v NullableSubnetCIDRReq) Get() *SubnetCIDRReq {
	return v.value
}

func (v *NullableSubnetCIDRReq) Set(val *SubnetCIDRReq) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnetCIDRReq) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnetCIDRReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnetCIDRReq(val *SubnetCIDRReq) *NullableSubnetCIDRReq {
	return &NullableSubnetCIDRReq{value: val, isSet: true}
}

func (v NullableSubnetCIDRReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnetCIDRReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


