/*
Azure IPAM

 Azure IPAM is a lightweight solution developed on top of the Azure platform designed to help Azure customers manage their enterprise IP Address space easily and effectively. 

API version: 3.4.0
Contact: ipam@microsoft.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExtSubnet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtSubnet{}

// ExtSubnet DOCSTRING
type ExtSubnet struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
	Cidr string `json:"cidr"`
	Endpoints []ExtEndpoint `json:"endpoints"`
}

type _ExtSubnet ExtSubnet

// NewExtSubnet instantiates a new ExtSubnet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtSubnet(name string, desc string, cidr string, endpoints []ExtEndpoint) *ExtSubnet {
	this := ExtSubnet{}
	this.Name = name
	this.Desc = desc
	this.Cidr = cidr
	this.Endpoints = endpoints
	return &this
}

// NewExtSubnetWithDefaults instantiates a new ExtSubnet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtSubnetWithDefaults() *ExtSubnet {
	this := ExtSubnet{}
	return &this
}

// GetName returns the Name field value
func (o *ExtSubnet) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ExtSubnet) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ExtSubnet) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *ExtSubnet) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *ExtSubnet) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *ExtSubnet) SetDesc(v string) {
	o.Desc = v
}

// GetCidr returns the Cidr field value
func (o *ExtSubnet) GetCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value
// and a boolean to check if the value has been set.
func (o *ExtSubnet) GetCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cidr, true
}

// SetCidr sets field value
func (o *ExtSubnet) SetCidr(v string) {
	o.Cidr = v
}

// GetEndpoints returns the Endpoints field value
func (o *ExtSubnet) GetEndpoints() []ExtEndpoint {
	if o == nil {
		var ret []ExtEndpoint
		return ret
	}

	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value
// and a boolean to check if the value has been set.
func (o *ExtSubnet) GetEndpointsOk() ([]ExtEndpoint, bool) {
	if o == nil {
		return nil, false
	}
	return o.Endpoints, true
}

// SetEndpoints sets field value
func (o *ExtSubnet) SetEndpoints(v []ExtEndpoint) {
	o.Endpoints = v
}

func (o ExtSubnet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtSubnet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["cidr"] = o.Cidr
	toSerialize["endpoints"] = o.Endpoints
	return toSerialize, nil
}

func (o *ExtSubnet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"cidr",
		"endpoints",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtSubnet := _ExtSubnet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtSubnet)

	if err != nil {
		return err
	}

	*o = ExtSubnet(varExtSubnet)

	return err
}

type NullableExtSubnet struct {
	value *ExtSubnet
	isSet bool
}

func (v NullableExtSubnet) Get() *ExtSubnet {
	return v.value
}

func (v *NullableExtSubnet) Set(val *ExtSubnet) {
	v.value = val
	v.isSet = true
}

func (v NullableExtSubnet) IsSet() bool {
	return v.isSet
}

func (v *NullableExtSubnet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtSubnet(val *ExtSubnet) *NullableExtSubnet {
	return &NullableExtSubnet{value: val, isSet: true}
}

func (v NullableExtSubnet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtSubnet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


